### PR TITLE
Extend functionality of receipts and transactions

### PR DESCRIPTION
**Pull request by mattrayner**
## Summary
* Added the ability to search for receipts by their status (open etc.)
* Taught receipts about transcations - you can now query a receipt for it's transactions
* Added the ability to find all transactions for a receipt ID

## Reasoning
I'm in the process of creating a tool that shows all receipts broken down by status and the items (transactions) that each is composed of. In order to do this I needed to add some additional functionality to the Receipt and Transaction classes.

### Note
Where possible I tried to follow the existing code style used within the project, if there are any changes you'd like me to make let me know and I'll do them ASAP 👍

### CODE REVIEW

**Comment by mattrayner** [comment]
It look like one of the CI builds failed because of a Travis error? Not sure how to work around that?

**Comment by kytrinyx** [comment]
It looks like the rubinius installation isn't available. We could try removing the `--binary` flag on that as Travis is suggesting in the log.

**Comment by kytrinyx** [comment]
I tried fiddling with the rubinius installation, and looking at the Travis docs to see if anything changed, but got nowhere useful. I've emailed Travis support about it.

**Comment by kytrinyx** [comment]
Thank you, @mattrayner. I ended up adding Rubinius to the "allow failures" list, as I couldn't figure out the magic incantation to get it to install on Travis.

**Comment by mattrayner** [comment]
Glad you managed to get it sorted! I'm still game for working on the Faraday implementation - unfortunately my laptop broke so I'm waiting for a new deliver from Apple - looks like it'll be mid-Jan 'till i'm back up and running

**Comment by kytrinyx** [comment]
@mattrayner that would be pretty awesome. Let me know if/when you get started and if you have any questions... it's been a loooong time but I'll see what I can do to help answer them.

**Comment by mattrayner** [comment]
Hey @kytrinyx - I'm back online and rearing to help 👍

Let me know if you have a pipeline of features you're interested in

**Pull request merged**
